-   id: check-commit-msg
    name: Check commit message
    description: Check that the commit message format matches the supplied regex
    entry: python -m hooks.check_commit_msg
    language: python
    stages: [commit-msg]